# Generated by Django 3.0.2 on 2020-02-03 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='external_letter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('si_no', models.IntegerField()),
                ('receipt_date', models.DateField()),
                ('fromm', models.CharField(choices=[('1', 'MHRD'), ('2', 'PMO'), ('3', 'NHPC')], max_length=1)),
                ('subject', models.CharField(max_length=50)),
                ('marked_to', models.CharField(max_length=100)),
                ('action_needed', models.CharField(max_length=300)),
                ('file', models.CharField(max_length=100)),
                ('remarks', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='internal_letter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('si_no', models.IntegerField()),
                ('in_date', models.DateField()),
                ('doc_type', models.CharField(choices=[('1', 'Notesheet'), ('2', 'File'), ('3', 'Letter Pad'), ('4', 'Plain Application'), ('5', 'Form/Leave Application'), ('6', 'Others')], max_length=1)),
                ('reference', models.CharField(max_length=50)),
                ('fromm', models.CharField(choices=[('1', 'Department'), ('2', 'Section'), ('3', 'Centre'), ('4', 'Others')], max_length=1)),
                ('out_date', models.DateField()),
                ('to', models.CharField(choices=[('1', 'Department'), ('2', 'Section'), ('3', 'Centre'), ('4', 'Others')], max_length=1)),
                ('subject', models.CharField(max_length=50)),
                ('remarks', models.CharField(max_length=500)),
            ],
        ),
    ]
